# Generated by Django 3.2.6 on 2021-08-09 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210809_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='size',
            field=models.CharField(choices=[('M', 'Medium(M)'), ('L', 'Large(L)'), ('XL', 'Extra Large(XL)'), ('XXL', 'Extra Extra Large(XXL)')], default='XL', max_length=20),
        ),
    ]
